/**
 * Investor Types & Schemas
 *
 * This file defines all data structures for the Investor CRM feature.
 *
 * WHAT IS A CRM?
 * - CRM stands for Customer Relationship Management
 * - For founders, we track INVESTOR relationships instead of customers
 * - It helps you keep track of who you've talked to, meeting notes, and next steps
 *
 * KEY CONCEPTS:
 * - Investor: A person/firm who might invest in your company
 * - Pipeline: The journey from "lead" to "closed" (like a sales funnel)
 * - Meeting: A scheduled call or meeting with an investor
 * - Interaction: Any touchpoint (email, call, note)
 */

import { z } from 'zod'

// ========================================
// INVESTOR TYPES
// ========================================

/**
 * What type of investor is this?
 *
 * Different investor types have different characteristics:
 * - Angel: Individual investors, usually write smaller checks ($10K-$250K)
 * - VC: Venture Capital firms, larger checks ($500K-$50M+)
 * - Family Office: Wealthy family's investment arm
 * - Corporate: Company investing strategically (e.g., Google Ventures)
 * - Accelerator: Programs like Y Combinator that invest + provide support
 */
export type InvestorType =
  | 'angel'
  | 'vc'
  | 'family_office'
  | 'corporate'
  | 'accelerator'
  | 'other'

/** Array version for dropdowns and validation */
export const INVESTOR_TYPES: InvestorType[] = [
  'angel',
  'vc',
  'family_office',
  'corporate',
  'accelerator',
  'other',
]

/** Human-readable labels for investor types */
export const INVESTOR_TYPE_LABELS: Record<InvestorType, string> = {
  angel: 'Angel Investor',
  vc: 'Venture Capital',
  family_office: 'Family Office',
  corporate: 'Corporate VC',
  accelerator: 'Accelerator',
  other: 'Other',
}

// ========================================
// PIPELINE STAGES
// ========================================

/**
 * Where is this investor in your fundraising pipeline?
 *
 * The pipeline represents the journey from first contact to closed deal:
 *
 * 1. lead: You've identified them as a potential investor
 * 2. contacted: You've reached out (cold email, intro, etc.)
 * 3. meeting_scheduled: You have a meeting on the calendar
 * 4. in_discussion: Active conversations happening
 * 5. due_diligence: They're doing deep dive on your company
 * 6. term_sheet: They've sent a term sheet (offer to invest)
 * 7. closed: Deal is done, money in bank!
 * 8. passed: They decided not to invest (not a bad thing - it's data)
 */
export type InvestorStage =
  | 'lead'
  | 'contacted'
  | 'meeting_scheduled'
  | 'in_discussion'
  | 'due_diligence'
  | 'term_sheet'
  | 'closed'
  | 'passed'

/** Array of stages in order (for the pipeline view) */
export const INVESTOR_STAGES: InvestorStage[] = [
  'lead',
  'contacted',
  'meeting_scheduled',
  'in_discussion',
  'due_diligence',
  'term_sheet',
  'closed',
  'passed',
]

/** Human-readable labels for each stage */
export const INVESTOR_STAGE_LABELS: Record<InvestorStage, string> = {
  lead: 'Lead',
  contacted: 'Contacted',
  meeting_scheduled: 'Meeting Scheduled',
  in_discussion: 'In Discussion',
  due_diligence: 'Due Diligence',
  term_sheet: 'Term Sheet',
  closed: 'Closed',
  passed: 'Passed',
}

/** Colors for each stage (for the Kanban board) */
export const INVESTOR_STAGE_COLORS: Record<InvestorStage, string> = {
  lead: 'bg-slate-100 text-slate-700',
  contacted: 'bg-blue-100 text-blue-700',
  meeting_scheduled: 'bg-cyan-100 text-cyan-700',
  in_discussion: 'bg-purple-100 text-purple-700',
  due_diligence: 'bg-amber-100 text-amber-700',
  term_sheet: 'bg-emerald-100 text-emerald-700',
  closed: 'bg-green-100 text-green-700',
  passed: 'bg-gray-100 text-gray-500',
}

// ========================================
// INVESTOR INTERFACE
// ========================================

/**
 * The main Investor interface.
 *
 * This represents an investor contact in your CRM.
 * Think of it like a detailed contact card.
 */
export interface Investor {
  /** Unique identifier (auto-generated by Firestore) */
  id: string

  /** Which organization this investor belongs to */
  orgId: string

  /** Investor's full name */
  name: string

  /** Type of investor (angel, VC, etc.) */
  type: InvestorType

  /** Their firm/company name (optional - angels might not have one) */
  firm?: string

  /** Email address for contact */
  email?: string

  /** Phone number */
  phone?: string

  /** LinkedIn profile URL */
  linkedInUrl?: string

  /** Twitter/X handle */
  twitterHandle?: string

  /** Their website */
  website?: string

  /** Current stage in your pipeline */
  stage: InvestorStage

  /**
   * Their typical check size range
   * Example: { min: 100000, max: 500000, currency: 'USD' }
   */
  checkSize?: {
    min: number
    max: number
    currency: string
  }

  /**
   * What areas/industries do they focus on?
   * Example: ['fintech', 'saas', 'b2b']
   */
  focusAreas?: string[]

  /**
   * What stage companies do they invest in?
   * Example: ['pre-seed', 'seed']
   */
  investmentStages?: string[]

  /** Free-form notes about this investor */
  notes?: string

  /** Who on your team is responsible for this relationship */
  assigneeId?: string
  assigneeName?: string

  /** When was the last interaction with this investor */
  lastContactAt?: string

  /** When should you follow up next */
  nextFollowUpAt?: string

  /** How did you find this investor? (referral, cold outreach, etc.) */
  source?: string

  /** Who referred them (if applicable) */
  referredBy?: string

  /** Priority level for outreach */
  priority?: 'low' | 'medium' | 'high'

  /** User who created this record */
  createdBy: string

  /** Timestamps (ISO strings for serialization) */
  createdAt: string
  updatedAt: string
}

// ========================================
// INVESTOR MEETING INTERFACE
// ========================================

/**
 * Types of meetings you might have with investors
 */
export type MeetingType =
  | 'intro'           // First meeting, getting to know each other
  | 'pitch'           // Formal pitch presentation
  | 'follow_up'       // Continuing previous conversation
  | 'due_diligence'   // Deep dive on your business
  | 'partner_meeting' // Meeting with VC partners (decision makers)
  | 'closing'         // Finalizing the deal
  | 'other'

export const MEETING_TYPES: MeetingType[] = [
  'intro',
  'pitch',
  'follow_up',
  'due_diligence',
  'partner_meeting',
  'closing',
  'other',
]

export const MEETING_TYPE_LABELS: Record<MeetingType, string> = {
  intro: 'Intro Call',
  pitch: 'Pitch Meeting',
  follow_up: 'Follow Up',
  due_diligence: 'Due Diligence',
  partner_meeting: 'Partner Meeting',
  closing: 'Closing',
  other: 'Other',
}

/**
 * Meeting outcome - how did it go?
 */
export type MeetingOutcome = 'positive' | 'neutral' | 'negative' | 'pending'

/**
 * Represents a meeting with an investor.
 */
export interface InvestorMeeting {
  /** Unique identifier */
  id: string

  /** Organization this belongs to */
  orgId: string

  /** Which investor this meeting is with */
  investorId: string

  /** Meeting title/subject */
  title: string

  /** Description or agenda */
  description?: string

  /** What type of meeting */
  meetingType: MeetingType

  /** When is the meeting */
  scheduledAt: string

  /** How long (in minutes) */
  duration: number

  /** Where (address or "Virtual") */
  location?: string

  /** Video call link (Zoom, Google Meet, etc.) */
  meetingUrl?: string

  /** List of attendee names/emails */
  attendees?: string[]

  /** How did it go? */
  outcome?: MeetingOutcome

  /** Meeting notes */
  notes?: string

  /** Action items from the meeting */
  actionItems?: string[]

  /** Who created this */
  createdBy: string

  /** Timestamps */
  createdAt: string
  updatedAt: string
}

// ========================================
// INVESTOR INTERACTION INTERFACE
// ========================================

/**
 * Types of interactions (touchpoints) with investors
 */
export type InteractionType =
  | 'email_sent'
  | 'email_received'
  | 'call'
  | 'meeting'
  | 'linkedin_message'
  | 'intro_request'
  | 'document_sent'
  | 'note'

export const INTERACTION_TYPES: InteractionType[] = [
  'email_sent',
  'email_received',
  'call',
  'meeting',
  'linkedin_message',
  'intro_request',
  'document_sent',
  'note',
]

export const INTERACTION_TYPE_LABELS: Record<InteractionType, string> = {
  email_sent: 'Email Sent',
  email_received: 'Email Received',
  call: 'Phone Call',
  meeting: 'Meeting',
  linkedin_message: 'LinkedIn Message',
  intro_request: 'Intro Request',
  document_sent: 'Document Sent',
  note: 'Note',
}

export const INTERACTION_ICONS: Record<InteractionType, string> = {
  email_sent: '📤',
  email_received: '📥',
  call: '📞',
  meeting: '🤝',
  linkedin_message: '💼',
  intro_request: '🔗',
  document_sent: '📎',
  note: '📝',
}

/**
 * Represents a single interaction with an investor.
 * This creates a timeline of all touchpoints.
 */
export interface InvestorInteraction {
  /** Unique identifier */
  id: string

  /** Organization this belongs to */
  orgId: string

  /** Which investor this interaction is with */
  investorId: string

  /** Type of interaction */
  type: InteractionType

  /** Subject line or title */
  subject: string

  /** Content/details of the interaction */
  content?: string

  /** If a document was shared, link to it */
  documentId?: string
  documentName?: string

  /** Who logged this interaction */
  createdBy: string
  createdByName?: string

  /** When did this happen */
  createdAt: string
}

// ========================================
// VALIDATION SCHEMAS
// ========================================

/**
 * Schema for creating a new investor.
 * Zod validates all the data before we save it.
 */
export const createInvestorSchema = z.object({
  name: z
    .string()
    .min(1, 'Name is required')
    .max(200, 'Name must be 200 characters or less'),

  type: z.enum(INVESTOR_TYPES as [InvestorType, ...InvestorType[]]),

  firm: z.string().max(200).optional(),

  email: z.string().email('Invalid email address').optional().or(z.literal('')),

  phone: z.string().max(50).optional(),

  linkedInUrl: z.string().url('Invalid URL').optional().or(z.literal('')),

  twitterHandle: z.string().max(50).optional(),

  website: z.string().url('Invalid URL').optional().or(z.literal('')),

  stage: z
    .enum(INVESTOR_STAGES as [InvestorStage, ...InvestorStage[]])
    .default('lead'),

  checkSize: z
    .object({
      min: z.number().min(0),
      max: z.number().min(0),
      currency: z.string().default('USD'),
    })
    .optional(),

  focusAreas: z.array(z.string()).optional(),

  investmentStages: z.array(z.string()).optional(),

  notes: z.string().max(10000).optional(),

  assigneeId: z.string().optional(),

  nextFollowUpAt: z.string().optional(),

  source: z.string().max(200).optional(),

  referredBy: z.string().max(200).optional(),

  priority: z.enum(['low', 'medium', 'high']).optional(),
})

/**
 * Schema for updating an investor.
 * All fields are optional since you might only update one thing.
 */
export const updateInvestorSchema = createInvestorSchema.partial()

/**
 * Schema for creating a meeting.
 */
export const createMeetingSchema = z.object({
  investorId: z.string().min(1, 'Investor is required'),

  title: z
    .string()
    .min(1, 'Title is required')
    .max(200, 'Title must be 200 characters or less'),

  description: z.string().max(5000).optional(),

  meetingType: z.enum(MEETING_TYPES as [MeetingType, ...MeetingType[]]),

  scheduledAt: z.string().min(1, 'Date/time is required'),

  duration: z.number().min(15).max(480).default(60), // 15 min to 8 hours

  location: z.string().max(500).optional(),

  meetingUrl: z.string().url('Invalid URL').optional().or(z.literal('')),

  attendees: z.array(z.string()).optional(),
})

/**
 * Schema for updating a meeting.
 */
export const updateMeetingSchema = createMeetingSchema.partial().extend({
  outcome: z.enum(['positive', 'neutral', 'negative', 'pending']).optional(),
  notes: z.string().max(10000).optional(),
  actionItems: z.array(z.string()).optional(),
})

/**
 * Schema for creating an interaction.
 */
export const createInteractionSchema = z.object({
  investorId: z.string().min(1, 'Investor is required'),

  type: z.enum(INTERACTION_TYPES as [InteractionType, ...InteractionType[]]),

  subject: z
    .string()
    .min(1, 'Subject is required')
    .max(500, 'Subject must be 500 characters or less'),

  content: z.string().max(10000).optional(),

  documentId: z.string().optional(),
  documentName: z.string().optional(),
})

// ========================================
// TYPE INFERENCE FROM SCHEMAS
// ========================================

export type CreateInvestorInput = z.infer<typeof createInvestorSchema>
export type UpdateInvestorInput = z.infer<typeof updateInvestorSchema>
export type CreateMeetingInput = z.infer<typeof createMeetingSchema>
export type UpdateMeetingInput = z.infer<typeof updateMeetingSchema>
export type CreateInteractionInput = z.infer<typeof createInteractionSchema>

// ========================================
// HELPER TYPES
// ========================================

/**
 * Investors grouped by pipeline stage (for Kanban view)
 */
export type InvestorsByStage = Record<InvestorStage, Investor[]>

/**
 * Group investors by their pipeline stage.
 *
 * @param investors - Array of investors to group
 * @returns Object with stages as keys and investor arrays as values
 */
export function groupInvestorsByStage(investors: Investor[]): InvestorsByStage {
  // Initialize all stages with empty arrays
  const grouped: InvestorsByStage = {
    lead: [],
    contacted: [],
    meeting_scheduled: [],
    in_discussion: [],
    due_diligence: [],
    term_sheet: [],
    closed: [],
    passed: [],
  }

  // Place each investor in the right group
  investors.forEach((investor) => {
    grouped[investor.stage].push(investor)
  })

  return grouped
}

/**
 * Get statistics about your investor pipeline.
 *
 * @param investors - Array of investors
 * @returns Stats object with counts and percentages
 */
export function getInvestorStats(investors: Investor[]) {
  const total = investors.length
  const byStage = groupInvestorsByStage(investors)

  // Count active (not passed or closed)
  const active = investors.filter(
    (i) => i.stage !== 'passed' && i.stage !== 'closed'
  ).length

  // Count needing follow-up (next follow-up date in the past)
  const now = new Date()
  const needsFollowUp = investors.filter((i) => {
    if (!i.nextFollowUpAt) return false
    return new Date(i.nextFollowUpAt) < now
  }).length

  return {
    total,
    active,
    needsFollowUp,
    byStage: {
      lead: byStage.lead.length,
      contacted: byStage.contacted.length,
      meeting_scheduled: byStage.meeting_scheduled.length,
      in_discussion: byStage.in_discussion.length,
      due_diligence: byStage.due_diligence.length,
      term_sheet: byStage.term_sheet.length,
      closed: byStage.closed.length,
      passed: byStage.passed.length,
    },
    // Conversion rate: closed / (closed + passed)
    conversionRate:
      byStage.closed.length + byStage.passed.length > 0
        ? Math.round(
            (byStage.closed.length /
              (byStage.closed.length + byStage.passed.length)) *
              100
          )
        : 0,
  }
}
